# Generated by Django 4.2.24 on 2025-09-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_cuisine_diet_favorite_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='carbs',
            field=models.FloatField(blank=True, help_text='Carbohydrates per serving (g)', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.FloatField(blank=True, help_text='Fat per serving (g)', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(blank=True, help_text='Protein per serving (g)', null=True),
        ),
    ]
