# Generated by Django 4.2.24 on 2025-09-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_carbs_recipe_fat_recipe_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for this recipe', null=True),
        ),
    ]
